INSERT INTO customers (
    customer_unique_id,
    zip_code_prefix,
    city,
    state
)
VALUES (
    uuid_generate_v4(),
    '01001',
    'Sao Paulo',
    'SP'
);

INSERT INTO sellers (
    zip_code_prefix,
    city,
    state
)
VALUES (
    '22041',
    'Rio de Janeiro',
    'RJ'
);

INSERT INTO orders (
    customer_id,
    order_status,
    purchase_timestamp,
    estimated_delivery_date,
    total_amount,
    shipping_address
)
VALUES (
    '11111111-1111-1111-1111-111111111111',

    'approved',

    CURRENT_TIMESTAMP,

    CURRENT_TIMESTAMP + INTERVAL '7 days',

    599.99,

    '{
      "street": "Av Paulista",
      "number": "1000",
      "city": "Sao Paulo",
      "state": "SP"
    }'
);

INSERT INTO payments (
    order_id,
    payment_sequential,
    payment_type,
    payment_installments,
    payment_value,
    payment_metadata
)
VALUES (
    '22222222-2222-2222-2222-222222222222',

    1,

    'credit_card',

    3,

    599.99,

    '{
      "gateway": "Stripe",
      "card_brand": "Visa"
    }'
);