CREATE INDEX idx_orders_customer
ON orders(customer_id);

CREATE INDEX idx_orders_purchase
ON orders(purchase_timestamp);

CREATE INDEX idx_payments_order
ON payments(order_id);

CREATE INDEX idx_orders_shipping_address
ON orders
USING GIN(shipping_address);

CREATE INDEX idx_payments_metadata
ON payments
USING GIN(payment_metadata);

CREATE INDEX idx_geolocation
ON geolocations
USING GIST(location);
